# CI
# [![CI](https://github.com/hahappyfu/FUnlock/actions/workflows/test.yml/badge.svg)](https://github.com/hahappyfu/FUnlock/actions/workflows/test.yml)

name: CI + Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: [macos-14, macos-15]
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        xcodebuild clean test \
          -project FUnlock.xcodeproj \
          -scheme FUnlock \
          -destination 'platform=macOS' \
          -enableCodeCoverage YES
